version: "3.8"

services:
  nginx:
    ports:
      # additional port for development
      - 8000:8000
  dashboard:
    image: runcitadel/dashboard
    build:
      context: ../dashboard
      target: development
    volumes:
      - ../dashboard:/app
      - "/app/node_modules"
    environment:
      DEVICE_HOSTNAME: ${DEVICE_HOSTNAME:-citadel-dev.local}
  ui:
    container_name: ui
    image: runcitadel/ui
    build:
      context: ../ui
      target: development
    volumes:
      - ../ui:/app
      - "/app/node_modules"
      - "/app/.next"
    env_file:
      - .env
    networks:
      default:
        ipv4_address: $DASHBOARD_NEW_IP
  manager:
    image: runcitadel/manager
    build:
      context: ../manager
      target: development
    volumes:
      # The following is required to correctly mount all services
      # inside so they are accessible to docker-compose otherwise
      # docker-in-docker fails becuase the compose file references
      # build contexts that don't exist inside this container.
      # - ${PWD}/..:${PWD}/..
      - ../manager:/app
      - "/app/node_modules"
    tty: true
    stdin_open: true
  middleware:
    image: runcitadel/middleware
    build:
      context: ../middleware
      target: development
    volumes:
      - ../middleware:/app
      - "/app/node_modules"
